name: Auto-Sign

on:
  schedule:
    - cron: "0 17 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eud_rocks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: node node_modules/puppeteer/install.js
    - run: echo "${{ secrets.ENV_FILE }}" > .env
    - run: npm run eud_rocks_checkin
  _1point3arces:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: node node_modules/puppeteer/install.js
    - run: echo "${{ secrets.ENV_FILE }}" > .env
    - run: npm run _1point3arces_checkin
