name: Auto-Checkin

on:
  schedule:
    - cron: "0 17 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eud_rocks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: add chinese fonts
      run: |
        sudo apt-get install ttf-mscorefonts-installer
        sudo apt-get install fontconfig
        fc-list :lang=zh
        ls -lh /usr/share/fonts/
        cp -rf ./fonts/* /usr/share/fonts/
        mkfontscale
        mkfontdir
        fc-cache
        fc-list :lang=zh

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    # - name: Install Dependencies
    #   run: npm install
    
    # - run: node node_modules/puppeteer/install.js
    
    - name: Import env file
      run: echo "${{ secrets.ENV_FILE }}" > .env
    # - run: npm run eud_rocks_checkin

    - name: Run script
      run: node eud_rocks.js

    # - name: Print result
    #   run: ls -lh ./snapshot

    # - name: Push snapshot
    #   run: |
    #     git config --global user.name 'a81884855'
    #     git config --global user.email 'garyguan0713@gmail.com'
    #     git add snapshot/
    #     git commit -am "push new snapshot"
    #     git push