name: Tests

on:
  schedule:
    - cron: "0 17 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: node node_modules/puppeteer/install.js
    - run: echo "${{ secrets.ENV_FILE }}" > .env
    - run: npm run eud_rocks_login
